//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWS.Log.Scripts {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class sScript {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal sScript() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FWS.Log.Scripts.sScript", typeof(sScript).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///IF NOT EXISTS (SELECT 1 FROM SYSOBJECTS WHERE NAME = &apos;FWSBUSTED&apos;)
        ///	BEGIN
        ///		CREATE TABLE FWSBUSTED
        ///		( 
        ///			logId                INTEGER  IDENTITY,
        ///			level				 SMALLINT NOT NULL,
        ///			data                 DATETIME NOT NULL,
        ///			classe               VARCHAR(50)  NULL,
        ///			metodo               VARCHAR(50)  NULL,
        ///			mensagem             VARCHAR(500)  NULL,
        ///			message              VARCHAR(500)  NULL,
        ///			stack                VARCHAR(500)  NULL
        ///		)
        ///
        ///		ALTER TABLE FWSBUSTED
        ///			ADD CONSTRAINT XPKlog P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FWSBUSTED_CREATE {
            get {
                return ResourceManager.GetString("FWSBUSTED_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///IF EXISTS (SELECT 1 FROM SYSOBJECTS WHERE NAME = &apos;FWSBUSTED&apos;)
        ///		DROP TABLE FWSBUSTED
        ///.
        /// </summary>
        internal static string FWSBUSTED_DROP {
            get {
                return ResourceManager.GetString("FWSBUSTED_DROP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///
        ///
        ///CREATE PROCEDURE USP_01_INSERT_BUSTED 
        ///	(
        ///		@LEVEL				  SMALLINT,
        ///		@CLASSE               VARCHAR(50)  = NULL,
        ///		@METODO               VARCHAR(50)  = NULL,
        ///		@MENSAGEM             VARCHAR(500) = NULL,
        ///		@MESSAGE              VARCHAR(500) = NULL,
        ///		@STACK                VARCHAR(500) = NULL
        ///	)
        ///AS 
        ///BEGIN
        ///	INSERT INTO LOG
        ///	( LEVEL, [DATA], CLASSE, METODO, MENSAGEM, MESSAGE, STACK )
        ///	VALUES
        ///	( @Level, GETDATE(), @CLASSE, @METODO, @MENSAGEM, @MESSAGE, @STACK ) 
        ///END
        ///.
        /// </summary>
        internal static string USP_01_INSERT_BUSTED_CREATE {
            get {
                return ResourceManager.GetString("USP_01_INSERT_BUSTED_CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS(SELECT 1 FROM log.sys.sysobjects WHERE name = &apos;USP_01_INSERT_BUSTED&apos;)
        ///BEGIN
        ///	DROP PROCEDURE USP_01_INSERT_BUSTED
        ///END
        ///.
        /// </summary>
        internal static string USP_01_INSERT_BUSTED_DROP {
            get {
                return ResourceManager.GetString("USP_01_INSERT_BUSTED_DROP", resourceCulture);
            }
        }
    }
}
