


CREATE PROCEDURE USP_01_INSERT_BUSTED 
	(
		@LEVEL				  SMALLINT,
		@CLASSE               VARCHAR(50)  = NULL,
		@METODO               VARCHAR(50)  = NULL,
		@MENSAGEM             VARCHAR(500) = NULL,
		@MESSAGE              VARCHAR(500) = NULL,
		@STACK                VARCHAR(500) = NULL
	)
AS 
BEGIN
	INSERT INTO FWSBUSTED
	( LEVEL, [DATA], CLASSE, METODO, MENSAGEM, MESSAGE, STACK )
	VALUES
	( @Level, GETDATE(), @CLASSE, @METODO, @MENSAGEM, @MESSAGE, @STACK ) 
END
