// <auto-generated />
namespace FWS.Dao.Migrations.Migrations_FWSVolcano
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class FWSVolcano : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FWSVolcano));
        
        string IMigrationMetadata.Id
        {
            get { return "201502280057009_FWSVolcano"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
