// <auto-generated />
namespace FWS.Dao.Migrations.Migrations_FwsCrew
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class FWSCrew : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FWSCrew));
        
        string IMigrationMetadata.Id
        {
            get { return "201502280056122_FWSCrew"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
