//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWS.Dictionary {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Mensages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FWS.Dictionary.Mensages", typeof(Mensages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe uma CNH válida.
        /// </summary>
        public static string CNHInvalida {
            get {
                return ResourceManager.GetString("CNHInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe um CNPJ válido.
        /// </summary>
        public static string CNPJInvalido {
            get {
                return ResourceManager.GetString("CNPJInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF informado ja esta sendo usado.
        /// </summary>
        public static string CPFInformadoJaEstaSendoUsado {
            get {
                return ResourceManager.GetString("CPFInformadoJaEstaSendoUsado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe um CPF válido.
        /// </summary>
        public static string CPFInvalido {
            get {
                return ResourceManager.GetString("CPFInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe um e-mail valido.
        /// </summary>
        public static string EmailInvalido {
            get {
                return ResourceManager.GetString("EmailInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o CEP.
        /// </summary>
        public static string InformeCep {
            get {
                return ResourceManager.GetString("InformeCep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe um CEP valido.
        /// </summary>
        public static string InformeCepValido {
            get {
                return ResourceManager.GetString("InformeCepValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe a CNH.
        /// </summary>
        public static string InformeCNH {
            get {
                return ResourceManager.GetString("InformeCNH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o CNPJ.
        /// </summary>
        public static string InformeCNPJ {
            get {
                return ResourceManager.GetString("InformeCNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infome o CPF.
        /// </summary>
        public static string InformeCPF {
            get {
                return ResourceManager.GetString("InformeCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o e-mail.
        /// </summary>
        public static string InformeEmail {
            get {
                return ResourceManager.GetString("InformeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o nome.
        /// </summary>
        public static string InformeNome {
            get {
                return ResourceManager.GetString("InformeNome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o RG.
        /// </summary>
        public static string InformeRG {
            get {
                return ResourceManager.GetString("InformeRG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe o telefone.
        /// </summary>
        public static string InformeTelefone {
            get {
                return ResourceManager.GetString("InformeTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe um telefone válido.
        /// </summary>
        public static string InformeTelefoneValido {
            get {
                return ResourceManager.GetString("InformeTelefoneValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informe um RG válido.
        /// </summary>
        public static string RGInvalido {
            get {
                return ResourceManager.GetString("RGInvalido", resourceCulture);
            }
        }
    }
}
