//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FWS.Dic {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class mError {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal mError() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FWS.Dic.mError", typeof(mError).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar conectar com o banco de dados..
        /// </summary>
        public static string BancoNaoEncontrado {
            get {
                return ResourceManager.GetString("BancoNaoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível executar o script no banco de dados..
        /// </summary>
        public static string ExecucaoQuerie {
            get {
                return ResourceManager.GetString("ExecucaoQuerie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foram encontradas as informações para a conexão com o banco de dados. .
        /// </summary>
        public static string InformacaoConexaoBanco {
            get {
                return ResourceManager.GetString("InformacaoConexaoBanco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider não informado no config da aplicação..
        /// </summary>
        public static string ProviderNaoInformado {
            get {
                return ResourceManager.GetString("ProviderNaoInformado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seção não localizada no config da aplicação..
        /// </summary>
        public static string SecaoNaoEncontrada {
            get {
                return ResourceManager.GetString("SecaoNaoEncontrada", resourceCulture);
            }
        }
    }
}
